# Generated by Django 3.2.5 on 2022-03-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_Board',
            fields=[
                ('rating_number', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('rating_content', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=0, max_length=5)),
            ],
            options={
                'db_table': 'rating_board',
            },
        ),
    ]
