# Generated by Django 3.2.5 on 2022-03-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_board', '0002_alter_rating_board_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_board',
            name='rating_number',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
