# Generated by Django 3.2.5 on 2022-03-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_board', '0003_alter_rating_board_rating_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_board',
            name='rating_number',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
