# Generated by Django 3.2.5 on 2022-03-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_board', '0004_alter_rating_board_rating_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating_board',
            name='rating_number',
        ),
        migrations.AddField(
            model_name='rating_board',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
