# Generated by Django 3.2.5 on 2022-03-31 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220330_1801'),
        ('rating_board', '0005_auto_20220331_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_board',
            name='userId',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
