# Generated by Django 3.2.5 on 2022-03-31 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_board', '0007_alter_rating_board_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_board',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
