# Generated by Django 3.2.5 on 2022-04-01 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        ('rating_board', '0008_alter_rating_board_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_board',
            name='movie_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
            preserve_default=False,
        ),
    ]
