# Generated by Django 3.2.5 on 2022-04-01 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_board', '0009_rating_board_movie_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating_board',
            name='movie_code',
        ),
    ]
