# Generated by Django 3.2.5 on 2022-03-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_number', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=200)),
                ('news_content', models.TextField(blank=True)),
                ('news_views', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
