# Generated by Django 3.2.5 on 2022-03-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_number',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
