# Generated by Django 3.2.5 on 2022-03-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_news_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_number',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
