# Generated by Django 3.2.5 on 2022-03-31 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220330_1801'),
        ('news', '0004_alter_news_news_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='admins',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
            preserve_default=False,
        ),
    ]
