# Generated by Django 3.2.5 on 2022-03-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_number',
        ),
        migrations.AddField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
