# Generated by Django 3.2.5 on 2022-03-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=30)),
                ('movie_overview', models.TextField()),
                ('movie_director', models.CharField(max_length=100)),
                ('movie_poster', models.CharField(max_length=100)),
                ('movie_company', models.CharField(max_length=50)),
                ('movie_opendt', models.DateField()),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
