# Generated by Django 3.2.5 on 2022-04-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('released_date', models.CharField(max_length=50)),
                ('popularity', models.FloatField(default=0)),
                ('vote_avg', models.FloatField(default=0)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=150)),
                ('genres', models.CharField(max_length=50)),
                ('actors', models.JSONField(default=[0, 0], null=True)),
                ('director', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
