# Generated by Django 3.2.5 on 2022-04-04 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='movie_code',
            field=models.ForeignKey(default=20220401, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.movie'),
            preserve_default=False,
        ),
    ]
